language: python
dist: xenial
arch:
  - amd64
  - arm64
python: 
  - 3.6
  - 3.8
services:
  - mysql
before_script:
  - sudo service mysql start
  - pip install django google protobuf
  - python setup.py install
  
script:
  - pytest
