language: python
dist: xenial
arch:
  - amd64
  - arm64
python: 
  - 3.6
  - 3.8
services:
  - mysql
before_script:
  - sudo service mysql start
  #- groupadd mysql
  - useradd -r -g mysql -s /bin/false mysql
  - cd /usr/local
  - tar zxvf /path/to/mysql-VERSION-OS.tar.gz
  - ln -s full-path-to-mysql-VERSION-OS mysql
  - cd mysql
  - mkdir mysql-files
  - chown mysql:mysql mysql-files
  - chmod 750 mysql-files
  - bin/mysqld --initialize --user=mysql
  - bin/mysql_ssl_rsa_setup
  - bin/mysqld_safe --user=mysql &
  - pip install django google protobuf
  - python setup.py install
  
script:
  - python unittests.py 
  #- pytest
